apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: matching-engine
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka
  - port: 9644
    name: admin
  selector:
    app: redpanda
